### ISSUE TITLE
bungee cord support

### ISSUE THREAD

**Issue by M1noa** [Overwrite987/UltimateServerProtector#31]
Possibly in the future the plugin can have a bungeecord version or support for bungeecord server?

**Comment by Overwrite987** [comment]
The answer is - probably no. And the reason for it - it's not safe.

The point is to protect users from problems directly on the spigot server, like getting permissions through hack plugins and such. 

If you install a plugin on a proxy, it destroys the whole point of the plugin as such.

If you need to support multiple servers so that you don't have to set the password separately on each of them - specify the full path to the folder with the data file.

If you need support for multiple servers so that you don't have to enter the password many times on different servers, you can use MySql addon. You can download it from the link: https://mega.nz/file/AjAxxAiC#AT9zHqrIL96bI5f2akVMwAPjdyzqiLNyUpfe8KZLoJ4

(There is no official release of the addon on mysql, but I plan to release it soon)
